"""Netatmo API objects."""

from ._common import (
    HomeObject,
    MappingObject,
    ModuleObject,
    Object,
    ObjectError,
    ObjectAttributeError,
    ObjectIdError,
    ObjectTypeError,
    RoomObject,
    SequenceObject,
)
from ._data import (
    HomeData,
    HomesData,
    ModuleData,
    ModulesData,
    RoomData,
    RoomsData,
    Schedule,
    Schedules,
    Timepoint,
    Timetable,
    Zone,
    Zones,
)
from ._status import HomeStatus, ModulesStatus, ModuleStatus, RoomsStatus, RoomStatus

__all__ = [
    "Object",
    "SequenceObject",
    "MappingObject",
    "HomeObject",
    "RoomObject",
    "ModuleObject",
    "HomesData",
    "HomeData",
    "RoomsData",
    "RoomData",
    "ModulesData",
    "ModuleData",
    "Schedules",
    "Schedule",
    "Timetable",
    "Timepoint",
    "Zones",
    "Zone",
    "HomeStatus",
    "RoomsStatus",
    "RoomStatus",
    "ModulesStatus",
    "ModuleStatus",
    "ObjectError",
    "ObjectAttributeError",
    "ObjectIdError",
    "ObjectTypeError",
]
